# Generated by Django 3.2.3 on 2021-06-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210621_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage_id',
            new_name='msg_id',
        ),
    ]
